import './src/utils/folders.js';
import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import { MONGO_URI, PORT } from './src/utils/env.js';
import fileUpload from 'express-fileupload';
import router from './src/router.js';
mongoose.connect(MONGO_URI);
const app = express();
app.use(cors());
app.use(express.json());
app.use(fileUpload());
app.use('/api', router);
app.listen(PORT);
